### ISSUE TITLE
Return a list of feed items

### ISSUE THREAD

**Issue by PorterHoskins** [More2Life/m2l-server#12]
The server should return a list of feed items for the user to browse through.

### Feed Item Types
- [ ] Video
- [ ] Event
- [ ] Product Listing

### Endpoint Spec:
`GET /feed`

##### Query Arguments:
- `count`: number of items the server should return (Optional)
- `index`: the place where the server should start when fetching the feed items (Optional)

##### Headers
- `Accept-Language`: The language the application is running in. Titles, descriptions, and any other user facing string should come down from the server translated in that language.

#### Feed Item Model
- `identifier`: The unique identifier of the item *String / GUID*
- `type`: The unique identifier of the item (`video`, `event`, `listing`) *String*
- `title`: The title / name of the item *String*
- `description` : The description of the content in the item *String*
- `index`: The position of the item in the feed. Used for sorting and paging. *Integer*
- `isActive`: Flag to display the item or not

#### Video Data Model 
*Inherits from Feed Item*
- `previewImageURL`: The url to the image for the frame of the video to show as a preview *String*
- `videoURL`: The url to the video stream *String*
- `publishDate`: The date the video was published *String*
- `views`: The number of times the video was viewed *Integer*

#### Event Data Model 
*Inherits from Feed Item*
- `coordinates`: The GPS coordinates to the event to show on the map *String*
- `address`: The street address of the location *String*
- `inviteURL`: The link to the event on Eventbrite

#### Listing Data Model 
*Inherits from Feed Item*
- `price`: The price of the product in USD *Float*
- `previewImageURL`: The url to the image for the product to show as a preview *String*

**Comment by PorterHoskins** [comment]
@dodgertodd @kingbrendann what do you guys think about this?

**Comment by PorterHoskins** [comment]
Updated it with product and Accept-Language

**Comment by PorterHoskins** [comment]
Updated with index on the Feed Item model

**Comment by dodgertodd** [comment]
I think I'd change `Product` into `Listing`. The `Product` model is going to be pretty key in the store. I think `Listing` has a `Product`. And a `Product` inheriting, for instance, `index` from `FeedItem` seems odd.

**Comment by dodgertodd** [comment]
I'm writing a RAML spec for this right now. It'll produce docs for us, run validations against schemas, can auto-generate test endpoints, and even skeleton endpoint code. It's pretty rad. Contracts ftw.

**Comment by M2LDev** [comment]
👍 agreed

**Comment by dodgertodd** [comment]
Another thing...should I pick on `feed` and `feedItem` ? Isn't the convention that a collection resource should be the pluralized version of the type of items in the collection? So it should be `feedItems` ? Worth it?

**Comment by PorterHoskins** [comment]
> Another thing...should I pick on feed and feedItem ? Isn't the convention that a collection resource should be the pluralized version of the type of items in the collection? So it should be feedItems ? Worth it?

Are you saying the `GET /feed` should be `GET /feedItems`? That works for me.

**Comment by PorterHoskins** [comment]
@dodgertodd we need to add `type` to the feed item so the parsers can know what it is. Added to the spec.

**Comment by PorterHoskins** [comment]
@dodgertodd Can you add it to the RAML?

**Comment by PorterHoskins** [comment]
We might want to add an optional query argument to the feed endpoint someday to pass a list of types if we want to support filtering.

**Comment by kingbrendann** [comment]
The event object should have a link to the Eventbrite page. They use that for ticketing and stuff.

**Comment by kingbrendann** [comment]
Let's close this.
